[project]
name = "clean-silver-computing-machine"
version = "0.1.0"
description = "AI research project using topology"
readme = "README.md"
requires-python = ">=3.11.11"
license = "GPL"
dependencies = [
    "jax",
    "scipy",
    "pandas",
    "matplotlib",
    "torch[rocm]",
    "mkl",
    "mkl-service",
    "torchvision",
    "tensorboard",
    "scikit-image",
    "opencv-contrib-python>=4.12.0.88",
]
